# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Song.destroy_all
Album.destroy_all
Artist.destroy_all
Genre.destroy_all
User.destroy_all

require 'open-uri'

guest = User.create!(
    username: "guest", 
    password: "password", 
    email: "eugene0688@yahoo.com", 
    name: "Chung money", 
    gender: "Male",
    birthday: "12/09/1993")


#Genres
glitchhop = Genre.create!({category: "Glitch Hop"})
dubstep = Genre.create!({category: "Dubstep"})
bassmusic = Genre.create!({category: "Bass Music"})
neurohop = Genre.create!({category: "Neuro Hop"})
downtempo = Genre.create!({category: "Downtempo"})
ambient = Genre.create!({category: "Ambient"})

#Artists
koansound = Artist.create!({name: "Koan Sound", bio: "Those funky brits", genre_id: glitchhop.id})
bassnectar = Artist.create!({name: "Bassnectar", bio: "A dj with really long hair", genre_id: dubstep.id})
detoxunit = Artist.create!({name: "Detox Unit", bio: "Tasteful bass music", genre_id: bassmusic.id})
kursa = Artist.create!({name: "Kursa", bio: "Crazy british dude", genre_id: neurohop.id})
tipper = Artist.create!({name: "Tipper", bio: "God tier electronic musician", genre_id: downtempo.id})
crunch = Artist.create!({name: "Crunch", bio: "Collaboration project between Tipper and Mike Wallis", genre_id: ambient.id})




#Albums
polychrome = Album.create!({name: "Polychrome", year: "2018", artist_id: koansound.id})
forward_escape = Album.create!({name: "Forward Escape", year: "2014", artist_id: tipper.id})
youcaneat = Album.create!({name: "YCEWYWFB", year: "2018", artist_id: kursa.id})
crunchalbum = Album.create!({name: "Crunch", year: "2013", artist_id: crunch.id})
deviate = Album.create!({name: "Deviate", year: "2019", artist_id: detoxunit.id})
cozzafrenzy = Album.create!({name: "Cozza Frenzy", year: "2009", artist_id: bassnectar.id})
bsjalbum = Album.create!({name: "Broken Soul Jamboree", year: "2010", artist_id: tipper.id})
undergroundcommunication = Album.create!({name: "Underground Communication", year: "2007", artist_id: bassnectar.id})


#Songs
uc1 = Song.create!({title: "Intro", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc2 = Song.create!({title: "Underground Communication", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc3 = Song.create!({title: "Bomb the Blocks", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc4 = Song.create!({title: "Amorphous Form", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc5 = Song.create!({title: "Ridiculous Wobble", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc6 = Song.create!({title: "Select Frequency", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc7 = Song.create!({title: "Kick It Complex (Bassnectar Remix)", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc8 = Song.create!({title: "Verbing the Noun", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc9 = Song.create!({title: "Yo", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc10 = Song.create!({title: "Stomp", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc11 = Song.create!({title: "Kick It Complex", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc12 = Song.create!({title: "Carried Away", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc13 = Song.create!({title: "Impossible and Overwhelming", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc14 = Song.create!({title: "I am Back (Bassnectar remix)", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc15 = Song.create!({title: "FSOF", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc16 = Song.create!({title: "Alkher illa Doffor (Bassnectar remix)", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
uc17 = Song.create!({title: "Kyrian Bee Bop", artist_id: bassnectar.id, album_id: undergroundcommunication.id})
bsj1 = Song.create!({title: "Big Question Small Head", artist_id: tipper.id, album_id: bsjalbum.id})
bsj2 = Song.create!({title: "Cuckoo", artist_id: tipper.id, album_id: bsjalbum.id})
bsj3 = Song.create!({title: "Class 5 Roaming Vapour", artist_id: tipper.id, album_id: bsjalbum.id})
bsj4 = Song.create!({title: "Brocken Spectre", artist_id: tipper.id, album_id: bsjalbum.id})
bsj5 = Song.create!({title: "Dead Soon", artist_id: tipper.id, album_id: bsjalbum.id})
bsj6 = Song.create!({title: "Cinder Cone", artist_id: tipper.id, album_id: bsjalbum.id})
bsj7 = Song.create!({title: "Herriot Method", artist_id: tipper.id, album_id: bsjalbum.id})
bsj8 = Song.create!({title: "Neuron Huskie", artist_id: tipper.id, album_id: bsjalbum.id})
bsj9 = Song.create!({title: "Tit For Tat", artist_id: tipper.id, album_id: bsjalbum.id})
bsj10 = Song.create!({title: "Reality Harshness Defender", artist_id: tipper.id, album_id: bsjalbum.id})
bsj11 = Song.create!({title: "Royal Dragon Sir", artist_id: tipper.id, album_id: bsjalbum.id})
bsj12 = Song.create!({title: "Hourglass Infringement", artist_id: tipper.id, album_id: bsjalbum.id})
cz1 = Song.create!({title: "Boombox", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz2 = Song.create!({title: "Cozza Frenzy (feat. Seasunz)", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz3 = Song.create!({title: "Cozza Frenzy (Mega Bass Remix)", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz4 = Song.create!({title: "The Churn of the Century", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz5 = Song.create!({title: "Love Here (Bassnectar Remix)", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz6 = Song.create!({title: "Backpack Rehab", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz7 = Song.create!({title: "Teleport Massive (feat. Zumbi)", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz8 = Song.create!({title: "West Coast Lo-Fi Rides Again", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz9 = Song.create!({title: "When I Grow Up (Bassnectar remix)", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz10 = Song.create!({title: "I am a Laser (feat. Double You)", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz11 = Song.create!({title: "Window Seat", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz12 = Song.create!({title: "I Wish I Was a Hipster", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz13 = Song.create!({title: "Are You Ready (feat. Capital J)", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
cz14 = Song.create!({title: "Boombox (Bassnectar_ill.Gates remix)", artist_id: bassnectar.id, album_id: cozzafrenzy.id})
detox1 = Song.create!({title: "Escape", artist_id: detoxunit.id, album_id: deviate.id})
detox2 = Song.create!({title: "Expand", artist_id: detoxunit.id, album_id: deviate.id})
detox3 = Song.create!({title: "Obscure", artist_id: detoxunit.id, album_id: deviate.id})
detox4 = Song.create!({title: "Adapt", artist_id: detoxunit.id, album_id: deviate.id})
detox5 = Song.create!({title: "Vibrate", artist_id: detoxunit.id, album_id: deviate.id})
fe1 = Song.create!({title: "Portal Spillage", artist_id: tipper.id, album_id: forward_escape.id})
fe2 = Song.create!({title: "Dreamsters", artist_id: tipper.id, album_id: forward_escape.id})
fe3 = Song.create!({title: "Homage Sliders", artist_id: tipper.id, album_id: forward_escape.id})
fe4 = Song.create!({title: "Table Flipping", artist_id: tipper.id, album_id: forward_escape.id})
fe5 = Song.create!({title: "Gulch", artist_id: tipper.id, album_id: forward_escape.id})
fe6 = Song.create!({title: "Grabbers Holders", artist_id: tipper.id, album_id: forward_escape.id})
fe7 = Song.create!({title: "The Bedraggling", artist_id: tipper.id, album_id: forward_escape.id})
fe8 = Song.create!({title: "Life Raft For A Death Trip", artist_id: tipper.id, album_id: forward_escape.id})
fe9 = Song.create!({title: "The Re-up", artist_id: tipper.id, album_id: forward_escape.id})
fe10 = Song.create!({title: "Apex of the Vortex", artist_id: tipper.id, album_id: forward_escape.id})
fe11 = Song.create!({title: "Rip Cord", artist_id: tipper.id, album_id: forward_escape.id})
fe12 = Song.create!({title: "Reverse Dross Maneuver", artist_id: tipper.id, album_id: forward_escape.id})
pc1 = Song.create!({title: "Viridian Dream", artist_id: koansound.id, album_id: polychrome.id})
pc2 = Song.create!({title: "Cobalt", artist_id: koansound.id, album_id: polychrome.id})
pc3 = Song.create!({title: "Hustle Hammer", artist_id: koansound.id, album_id: polychrome.id})
pc4 = Song.create!({title: "Chalk It Out", artist_id: koansound.id, album_id: polychrome.id})
pc5 = Song.create!({title: "Chilli Daddy", artist_id: koansound.id, album_id: polychrome.id})
pc6 = Song.create!({title: "Virtual Light", artist_id: koansound.id, album_id: polychrome.id})
pc7 = Song.create!({title: "Prism Pulse", artist_id: koansound.id, album_id: polychrome.id})
pc8 = Song.create!({title: "Hydroplane", artist_id: koansound.id, album_id: polychrome.id})
pc9 = Song.create!({title: "Jongmyo", artist_id: koansound.id, album_id: polychrome.id})
pc10 = Song.create!({title: "Drift", artist_id: koansound.id, album_id: polychrome.id})
pc11 = Song.create!({title: "The Zulla", artist_id: koansound.id, album_id: polychrome.id})
crunch1 = Song.create!({title: "Grama", artist_id: crunch.id, album_id: crunchalbum.id})
crunch2 = Song.create!({title: "Sponge", artist_id: crunch.id, album_id: crunchalbum.id})
crunch3 = Song.create!({title: "Amlma", artist_id: crunch.id, album_id: crunchalbum.id})
crunch4 = Song.create!({title: "Pollen", artist_id: crunch.id, album_id: crunchalbum.id})
crunch5 = Song.create!({title: "Emedr", artist_id: crunch.id, album_id: crunchalbum.id})
crunch6 = Song.create!({title: "Crumb", artist_id: crunch.id, album_id: crunchalbum.id})
crunch7 = Song.create!({title: "Stem", artist_id: crunch.id, album_id: crunchalbum.id})
crunch8 = Song.create!({title: "Lobot", artist_id: crunch.id, album_id: crunchalbum.id})
crunch9 = Song.create!({title: "Art Pylon", artist_id: crunch.id, album_id: crunchalbum.id})
crunch10 = Song.create!({title: "Welt", artist_id: crunch.id, album_id: crunchalbum.id})
crunch11 = Song.create!({title: "Catalon", artist_id: crunch.id, album_id: crunchalbum.id})
crunch12 = Song.create!({title: "MadeVke", artist_id: crunch.id, album_id: crunchalbum.id})
crunch13 = Song.create!({title: "Toe Tac", artist_id: crunch.id, album_id: crunchalbum.id})
crunch14 = Song.create!({title: "Snuff", artist_id: crunch.id, album_id: crunchalbum.id})
crunch15 = Song.create!({title: "Werds", artist_id: crunch.id, album_id: crunchalbum.id})
kursa1 = Song.create!({title: "Introduction", artist_id: kursa.id, album_id: youcaneat.id})
kursa2 = Song.create!({title: "Phlabby Fries", artist_id: kursa.id, album_id: youcaneat.id})
kursa3 = Song.create!({title: "CanYaTho", artist_id: kursa.id, album_id: youcaneat.id})
kursa4 = Song.create!({title: "A view to forget", artist_id: kursa.id, album_id: youcaneat.id})
kursa5 = Song.create!({title: "Green Steal Spork", artist_id: kursa.id, album_id: youcaneat.id})
kursa6 = Song.create!({title: "Wifey", artist_id: kursa.id, album_id: youcaneat.id})
kursa7 = Song.create!({title: "Dustika", artist_id: kursa.id, album_id: youcaneat.id})
kursa8 = Song.create!({title: "On The Canz", artist_id: kursa.id, album_id: youcaneat.id})
kursa9 = Song.create!({title: "Coldest Blue", artist_id: kursa.id, album_id: youcaneat.id})
kursa10 = Song.create!({title: "Itago", artist_id: kursa.id, album_id: youcaneat.id})

# Mp3
uctrack1 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/01+Intro.mp3')
uctrack2 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/02+Underground+Communication+(feat..mp3')
uctrack3 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/03+Bomb+the+Blocks+(feat.+Persia).mp3')
uctrack4 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/04+Amorphous+Form+(feat.+Souleye+_+E.mp3')
uctrack5 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/05+Ridiculous+Wobble+(feat.+Nibu).mp3')
uctrack6 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/06+Select+Frequency+(feat.+Seasunz).mp3')
uctrack7 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/07+Kick+It+Complex+(Bassnectar+remix.mp3')
uctrack8 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/08+Verbing+the+Noun.mp3')
uctrack9 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/09+Yo+(feat.+KristinaMaria).mp3')
uctrack10 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/10+Stomp+(feat.+Seasunz).mp3')
uctrack11 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/11+Kick+It+Complex+(feat.+Persia).mp3')
uctrack12 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/12+Carried+Away.mp3')
uctrack13 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/13+Impossible+and+Overwhelming.mp3')
uctrack14 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/14+I+Am+Back+(Bassnectar+remix).mp3')
uctrack15 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/15+FSOF.mp3')
uctrack16 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/16+Alkher+Illa+Doffor+(Bassnectar+re.mp3')
uctrack17 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Bassnectar+-+Underground+Communication/17+Kyrian+Bee+Bop.mp3')
bsjtrack1 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/01+-+Tipper+-+Big+Question+small+head.mp3')
bsjtrack2 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/02+-+Tipper+-+Cuckoo.mp3')
bsjtrack3 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/03+-+Tipper+-+Class+5+Roaming+Vapour.mp3')
bsjtrack4 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/04+-+Tipper+-+Brocken+Spectre.mp3')
bsjtrack5 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/05+-+Tipper+-+Dead+Soon.mp3')
bsjtrack6 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/06+-+Tipper+-+Cinder+Cone.mp3')
bsjtrack7 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/07+-+Tipper+-+Herriot+Method.mp3')
bsjtrack8 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/08+-+Tipper+-+Neuron+Huskie.mp3')
bsjtrack9 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/09+-+Tipper+-+Tit+For+Tat.mp3')
bsjtrack10 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/10+-+Tipper+-+Reality+Harshness+Defender.mp3')
bsjtrack11 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/11+-+Tipper+-+Royal+Dragon+Sir.mp3')
bsjtrack12 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Broken+Soul+Jamboree+(2010)/12+-+Tipper+-+Hourglass+Infringement.mp3')
# cztrack1 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/01+Boombox.mp3')
# cztrack2 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/02+Cozza+Frenzy+(feat.+Seasunz).mp3')
# cztrack3 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/03+Cozza+Frenzy+(Mega+Bass+Remix).mp3')
# cztrack4 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/04+The+Churn+of+the+Century.mp3')
# cztrack5 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/05+Love+Here+(Bassnectar+remix).mp3')
# cztrack6 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/06+Backpack+Rehab+(feat.+Cates+_+DPL).mp3')
# cztrack7 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/07+Teleport+Massive+(feat.+Zumbi).mp3')
# cztrack8 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/08+West+Coast+Lo-Fi+Rides+Again.mp3')
# cztrack9 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/09+When+I+Grow+Up+(Bassnectar+remix).mp3')
# cztrack10 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/10+I+Am+a+Laser+(feat.+Double+You).mp3')
# cztrack11 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/11+Window+Seat.mp3')
# cztrack12 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/12+I+Wish+I+Was+a+Hipster.mp3')
# cztrack13 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/13+Are+You+Ready+(feat.+Capital+J).mp3')
# cztrack14 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Cozza+Frenzy/14+Boombox+(Bassnectar+_+iLL.Gates+remix).mp3')
deviate1 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Detox+Unit+-+Deviate/Detox+Unit+-+Deviate+-+01+Escape.mp3')
deviate2 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Detox+Unit+-+Deviate/Detox+Unit+-+Deviate+-+02+Expand.mp3')
deviate3 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Detox+Unit+-+Deviate/Detox+Unit+-+Deviate+-+03+Obscure.mp3')
deviate4 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Detox+Unit+-+Deviate/Detox+Unit+-+Deviate+-+04+Adapt.mp3')
deviate5 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Detox+Unit+-+Deviate/Detox+Unit+-+Deviate+-+05+Vibrate.mp3')
fetrack1 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/01_Portal+Spillage_Tipper.mp3')
fetrack2 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/02_Dreamsters_Tipper.mp3')
fetrack3 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/03_Homage+Sliders_Tipper.mp3')
fetrack4 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/04_Table+Flipping_Tipper.mp3')
fetrack5 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/05_Gulch_Tipper.mp3')
fetrack6 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/06_Grabbers+Holders_Tipper.mp3')
fetrack7 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/07_The+Bedraggling_Tipper.mp3')
fetrack8 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/08_Life+Raft+For+A+Death+Trip_Tipper.mp3')
fetrack9 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/09_The+Re-Up_Tipper.mp3')
fetrack10 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/10_Apex+Of+The+Vortex_Tipper.mp3')
fetrack11 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/11_Rip+Cord_Tipper.mp3')
fetrack12 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Forward+Escape/12_Reverse+Dross+Maneuver_Tipper.mp3')
pctrack1 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOANSound-ViridianDream.mp3')
pctrack2 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+01+Cobalt.mp3')
pctrack3 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+02+Hustle+Hammer.mp3')
pctrack4 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+03+Chalk+It+Out.mp3')
pctrack5 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+04+Chilli+Daddy.mp3')
pctrack6 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+05+Virtual+Light.mp3')
pctrack7 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+07+Prism+Pulse.mp3')
pctrack8 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+08+Hydroplane.mp3')
pctrack9 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+09+Jongmyo.mp3')
pctrack10 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+10+Drift.mp3')
pctrack11 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Koan+Sound+-+Polychrome/KOAN+Sound+-+Polychrome+-+11+The+Zulla.mp3')
# kursatrack1 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+01+Introduction.mp3')
# kursatrack2 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+02+Phlabby+Fries.mp3')
# kursatrack3 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+03+CANYATHO.mp3')
# kursatrack4 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+04+a+view+to+forget.mp3')
# kursatrack5 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+05+Green+Steal+Spork.mp3')
# kursatrack6 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+06+Wifey.mp3')
# kursatrack7 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+07+Dustika.mp3')
# kursatrack8 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+08+On+The+Canz.mp3')
# kursatrack9 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+09+Coldest+Blue.mp3')
# kursatrack10 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Kursa+-+Y.C.E.W.E.Y.WFB/Kursa+-+YOU+CAN+EAT+WHATEVER+YOU+WANT+FOR+BREAKFAST+PART+3+(The+Final+Course)+-+10+ITAGO.mp3')
# crunchtrack1 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/01+-+Crunch+-+Grama.mp3')
# crunchtrack2 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/02+-+Crunch+-+Sponge.mp3')
# crunchtrack3 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/03+-+Crunch+-+Am.L.Ma.mp3')
# crunchtrack4 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/04+-+Crunch+-+Pollen.mp3')
# crunchtrack5 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/05+-+Crunch+-+Emedr.L.mp3')
# crunchtrack6 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/06+-+Crunch+-+Crumb.mp3')
# crunchtrack7 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/07+-+Crunch+-+Stem.T.L.mp3')
# crunchtrack8 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/08+-+Crunch+-+Lobot.mp3')
# crunchtrack9 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/09+-+Crunch+-+Art+Pylon.mp3')
# crunchtrack10 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/10+-+Crunch+-+Welt.mp3')
# crunchtrack11 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/11+-+Crunch+-+Catalon.mp3')
# crunchtrack12= open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/12+-+Crunch+-+Made+V.ke.mp3')
# crunchtrack13 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/13+-+Crunch+-+Toe+Tac+T.c.mp3')
# crunchtrack14 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/14+-+Crunch+-+Snuff.mp3')
# crunchtrack15 = open('https://dropify-aa-seeds.s3.us-east-2.amazonaws.com/dropify_seed_data/Tipper+and+Mike+Wallis+-+Crunch+1/15+-+Crunch+-+Werds.mp3')


#Amazon S3 Song Attachments
uc1.mp3.attach(io: uctrack1, filename: '01 Intro.mp3')
uc2.mp3.attach(io: uctrack2, filename: '02 Underground Communication (feat..mp3')
uc3.mp3.attach(io: uctrack3, filename: '03 Bomb the Blocks (feat. Persia).mp3')
uc4.mp3.attach(io: uctrack4, filename: '04 Amorphous Form (feat. Souleye _ E.mp3')
uc5.mp3.attach(io: uctrack5, filename: '05 Ridiculous Wobble (feat. Nibu).mp3')
uc6.mp3.attach(io: uctrack6, filename: '06 Select Frequency (feat. Seasunz).mp3')
uc7.mp3.attach(io: uctrack7, filename: '07 Kick It Complex (Bassnectar remix.mp3')
uc8.mp3.attach(io: uctrack8, filename: '08 Verbing the Noun.mp3')
uc9.mp3.attach(io: uctrack9, filename: '09 Yo (feat. KristinaMaria).mp3')
uc10.mp3.attach(io: uctrack10, filename: '10 Stomp (feat. Seasunz).mp3')
uc11.mp3.attach(io: uctrack11, filename: '11 Kick It Complex (feat. Persia).mp3')
uc12.mp3.attach(io: uctrack12, filename: '12 Carried Away.mp3')
uc13.mp3.attach(io: uctrack13, filename: '13 Impossible and Overwhelming.mp3')
uc14.mp3.attach(io: uctrack14, filename: '14 I Am Back (Bassnectar remix).mp3')
uc15.mp3.attach(io: uctrack15, filename: '15 FSOF.mp3')
uc16.mp3.attach(io: uctrack16, filename: '16 Alkher Illa Doffor (Bassnectar re.mp3')
uc17.mp3.attach(io: uctrack17, filename: '17 Kyrian Bee Bop.mp3')
bsj1.mp3.attach(io: bsjtrack1, filename: '01 - Tipper - Big Question small head.mp3')
bsj2.mp3.attach(io: bsjtrack2, filename: '02 - Tipper - Cuckoo.mp3')
bsj3.mp3.attach(io: bsjtrack3, filename: '03 - Tipper - Class 5 Roaming Vapour.mp3')
bsj4.mp3.attach(io: bsjtrack4, filename: '04 - Tipper - Brocken Spectre.mp3')
bsj5.mp3.attach(io: bsjtrack5, filename: '05 - Tipper - Dead Soon.mp3')
bsj6.mp3.attach(io: bsjtrack6, filename: '06 - Tipper - Cinder Cone.mp3')
bsj7.mp3.attach(io: bsjtrack7, filename: '07 - Tipper - Herriot Method.mp3')
bsj8.mp3.attach(io: bsjtrack8, filename: '08 - Tipper - Neuron Huskie.mp3')
bsj9.mp3.attach(io: bsjtrack9, filename: '09 - Tipper - Tit For Tat.mp3')
bsj10.mp3.attach(io: bsjtrack10, filename: '10 - Tipper - Reality Harshness Defender.mp3')
bsj11.mp3.attach(io: bsjtrack11, filename: '11 - Tipper - Royal Dragon Sir.mp3')
bsj12.mp3.attach(io: bsjtrack12, filename: '12 - Tipper - Hourglass Infringement.mp3')
# cz1.mp3.attach(io: cztrack1, filename: '01 Boombox.mp3')
# cz2.mp3.attach(io: cztrack2, filename: '02 Cozza Frenzy (feat. Seasunz).mp3')
# cz3.mp3.attach(io: cztrack3, filename: '03 Cozza Frenzy (Mega Bass Remix).mp3')
# cz4.mp3.attach(io: cztrack4, filename: '04 The Churn of the Century.mp3')
# cz5.mp3.attach(io: cztrack5, filename: '05 Love Here (Bassnectar remix).mp3')
# cz6.mp3.attach(io: cztrack6, filename: '06 Backpack Rehab (feat. Cates _ DPL).mp3')
# cz7.mp3.attach(io: cztrack7, filename: '07 Teleport Massive (feat. Zumbi).mp3')
# cz8.mp3.attach(io: cztrack8, filename: '08 West Coast Lo-Fi Rides Again.mp3')
# cz9.mp3.attach(io: cztrack9, filename: '09 When I Grow Up (Bassnectar remix).mp3')
# cz10.mp3.attach(io: cztrack10, filename: '10 I Am a Laser (feat. Double You).mp3')
# cz11.mp3.attach(io: cztrack11, filename: '11 Window Seat.mp3')
# cz12.mp3.attach(io: cztrack12, filename: '12 I Wish I Was a Hipster.mp3')
# cz13.mp3.attach(io: cztrack13, filename: '13 Are You Ready (feat. Capital J).mp3')
# cz14.mp3.attach(io: cztrack14, filename: '14 Boombox (Bassnectar _ iLL.Gates remix).mp3')
detox1.mp3.attach(io: deviate1, filename: 'Detox Unit - Deviate - 01 Escape.mp3')
detox2.mp3.attach(io: deviate2, filename: 'Detox Unit - Deviate - 02 Expand.mp3')
detox3.mp3.attach(io: deviate3, filename: 'Detox Unit - Deviate - 03 Obscure.mp3')
detox4.mp3.attach(io: deviate4, filename: 'Detox Unit - Deviate - 04 Adapt.mp3')
detox5.mp3.attach(io: deviate5, filename: 'Detox Unit - Deviate - 05 Vibrate.mp3')
fe1.mp3.attach(io: fetrack1, filename: '01_Portal Spillage_Tipper.mp3')
fe2.mp3.attach(io: fetrack2, filename: '02_Dreamsters_Tipper.mp3')
fe3.mp3.attach(io: fetrack3, filename: '03_Homage Sliders_Tipper.mp3')
fe4.mp3.attach(io: fetrack4, filename: '04_Table Flipping_Tipper.mp3')
fe5.mp3.attach(io: fetrack5, filename: '05_Gulch_Tipper.mp3')
fe6.mp3.attach(io: fetrack6, filename: '06_Grabbers Holders_Tipper.mp3')
fe7.mp3.attach(io: fetrack7, filename: '07_The Bedraggling_Tipper.mp3')
fe8.mp3.attach(io: fetrack8, filename: '08_Life Raft For A Death Trip_Tipper.mp3')
fe9.mp3.attach(io: fetrack9, filename: '09_The Re-Up_Tipper.mp3')
fe10.mp3.attach(io: fetrack10, filename: '10_Apex Of The Vortex_Tipper.mp3')
fe11.mp3.attach(io: fetrack11, filename: '11_Rip Cord_Tipper.mp3')
fe12.mp3.attach(io: fetrack12, filename: '12_Reverse Dross Maneuver_Tipper.mp3')
pc1.mp3.attach(io: pctrack1, filename: 'KOANSound-ViridianDream.mp3')
pc2.mp3.attach(io: pctrack2, filename: 'KOAN Sound - Polychrome - 01 Cobalt.mp3')
pc3.mp3.attach(io: pctrack3, filename: 'KOAN Sound - Polychrome - 02 Hustle Hammer.mp3')
pc4.mp3.attach(io: pctrack4, filename: 'KOAN Sound - Polychrome - 03 Chalk It Out.mp3')
pc5.mp3.attach(io: pctrack5, filename: 'KOAN Sound - Polychrome - 04 Chilli Daddy.mp3')
pc6.mp3.attach(io: pctrack6, filename: 'KOAN Sound - Polychrome - 05 Virtual Light.mp3')
pc7.mp3.attach(io: pctrack7, filename: 'KOAN Sound - Polychrome - 07 Prism Pulse.mp3')
pc8.mp3.attach(io: pctrack8, filename: 'KOAN Sound - Polychrome - 08 Hydroplane.mp3')
pc9.mp3.attach(io: pctrack9, filename: 'KOAN Sound - Polychrome - 09 Jongmyo.mp3')
pc10.mp3.attach(io: pctrack10, filename: 'KOAN Sound - Polychrome - 10 Drift.mp3')
pc11.mp3.attach(io: pctrack11, filename: 'KOAN Sound - Polychrome - 11 The Zulla.mp3')
# kursa1.mp3.attach(io: kursatrack1, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 01 Introduction.mp3')
# kursa2.mp3.attach(io: kursatrack2, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 02 Phlabby Fries.mp3')
# kursa3.mp3.attach(io: kursatrack3, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 03 CANYATHO.mp3')
# kursa4.mp3.attach(io: kursatrack4, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 04 a view to forget.mp3')
# kursa5.mp3.attach(io: kursatrack5, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 05 Green Steal Spork.mp3')
# kursa6.mp3.attach(io: kursatrack6, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 06 Wifey.mp3')
# kursa7.mp3.attach(io: kursatrack7, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 07 Dustika.mp3')
# kursa8.mp3.attach(io: kursatrack8, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 08 On The Canz.mp3')
# kursa9.mp3.attach(io: kursatrack9, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 09 Coldest Blue.mp3')
# kursa10.mp3.attach(io: kursatrack10, filename: 'Kursa - YOU CAN EAT WHATEVER YOU WANT FOR BREAKFAST PART 3 (The Final Course) - 10 ITAGO.mp3')
# crunch1.mp3.attach(io: crunchtrack1, filename: '01 - Crunch - Grama.mp3')
# crunch2.mp3.attach(io: crunchtrack2, filename: '02 - Crunch - Sponge.mp3')
# crunch3.mp3.attach(io: crunchtrack3, filename: '03 - Crunch - Am.L.Ma.mp3')
# crunch4.mp3.attach(io: crunchtrack4, filename: '04 - Crunch - Pollen.mp3')
# crunch5.mp3.attach(io: crunchtrack5, filename: '05 - Crunch - Emedr.L.mp3')
# crunch6.mp3.attach(io: crunchtrack6, filename: '06 - Crunch - Crumb.mp3')
# crunch7.mp3.attach(io: crunchtrack7, filename: '07 - Crunch - Stem.T.L.mp3')
# crunch8.mp3.attach(io: crunchtrack8, filename: '08 - Crunch - Lobot.mp3')
# crunch9.mp3.attach(io: crunchtrack9, filename: '09 - Crunch - Art Pylon.mp3')
# crunch10.mp3.attach(io: crunchtrack10, filename: '10 - Crunch - Welt.mp3')
# crunch11.mp3.attach(io: crunchtrack11, filename: '11 - Crunch - Catalon.mp3')
# crunch12.mp3.attach(io: crunchtrack12, filename: '12 - Crunch - Made V.ke.mp3')
# crunch13.mp3.attach(io: crunchtrack13, filename: '13 - Crunch - Toe Tac T.c.mp3')
# crunch14.mp3.attach(io: crunchtrack14, filename: '14 - Crunch - Snuff.mp3')
# crunch15.mp3.attach(io: crunchtrack15, filename: '15 - Crunch - Werds.mp3')





